export enum Action {
    FETCH_CLOTHING_ITEMS,
    UPDATE_CLOTHING_ITEM,
    CREATE_CLOTHING_ITEM,
    REMOVE_CLOTHING_ITEM,

    FETCH_ORDERS,
    CREATE_ORDER,
    COMPLETE_ORDER,

    ADD_TO_CART,
    REMOVE_FROM_CART,

    FETCH_CATEGORIES,
    CREATE_CATEGORY,
}
